tipos = {}
tipos["usuário"] = {"importância": 1, "cor": "red"}
tipos["switch_ramificação"] = {"importância": 2, "cor": "blue"}
tipos["switch_departamento"] = {"importância": 3, "cor": "gray"}
tipos["pap"] = {"importância": 3, "cor": "yellow"},
tipos["switch_prédio"] = {"importância": 5, "cor": "green"}
tipos["onu"] = {"importância": 8, "cor": "purple"}
tipos["roteador"] = {"importância": 8, "cor": "gold"}
tipos["olt"] = {"importância": 13, "cor": "orange"}
tipos["switch_olt"] = {"importância": 21, "cor": "cyan"}
tipos["rtb"] = {"importância": 34, "cor": "magenta"}
tipos["servidor"] = {"importância": 55, "cor": "brown"}
tipos["wan"] = {"importância": 89, "cor": "lime"}
